### ISSUE TITLE
Comparison with more popular libraries

### ISSUE THREAD

**Issue by dandv** [dutu/poloniex-api-node#1]
Salut, thanks for releasing this library.

How does it compare with more established libraries?
- @tylerfilla's https://github.com/tylerfilla/node-poloniex-unofficial
- @rferro's https://github.com/rferro/plnx
- @premasagar's https://github.com/premasagar/poloniex.js

Background: https://pinboard.in/u:dandv/b:19ae24e7f634

**Comment by dutu** [comment]
@dandv , see [CHANGELOG.md](https://github.com/dutu/poloniex-api-node/blob/master/CHANGELOG.md#100---2016-10-05)

It looks that other libraries are more than simple wrappers, i.e. should support parameters as defined by the native API's, rather than handling the parameters, setting defaults, handling parameter errors.

This wrapper sends the parameters to the poloniex API, which allows the response from the poloniex server to be passed back to the user without interference. 

Unfortunately due to the way the other libraries are structured and parameter passing constructed, PR are not possible without significant non-backward compatible changes.
