### ISSUE TITLE
Poloniex error 403 Security Check

### ISSUE THREAD

**Issue by tyndallm** [dutu/poloniex-api-node#2]
Hey, I keep getting a 403 error which returns the security check screen. Is there some way to get around this? Have you encountered this when using your wrapper?

**Comment by dutu** [comment]
The error is returned directly by Poloniex web server. 
I haven't been able to reproduce it. Can you provide more details (e.g. which API method you are using, do you get it for every single API call or only sporadically, ...)?

**Comment by dutu** [comment]
I will close this issue since the error is returned from Poloniex web server and there is no additional information to investigate more.
If the issue comes back again, please provide more detailed info: under what condition is the error received, it for every single API call or only sporadically, does it occur for all methods or not, etc...

**Comment by creativecuriosity** [comment]
Had this error as well. 
It is user error; though it could be reduced by adding some parameter checking.

When a user sends in a request that requires an additional parameter, for instance returnCompleteBalances(cb), instead of returnCompleteBalances('all',cb), the error is returned as 403 Forbidden, invalid key/secret.

**Comment by dutu** [comment]
fixed in version 1.3.1

**Comment by JBaczuk** [comment]
I'm getting this error with v. 1.7.0 when trying to call:

```
ctx.api.returnCompleteBalances('all', function (err, data) {
})
```

Do I have the parameters wrong?

**Comment by dutu** [comment]
@JBaczuk your custom nonce function should return the nonce value
`return new Date().getTime()`
