### ISSUE TITLE
Number of calls is not throttled

### ISSUE THREAD

**Issue by Goswinus** [dutu/poloniex-api-node#25]
Not really an issue, nor a bug, but the Poloniex API doesn't like to be called more then 8 times per second.
I have tweeked my copy of your excellent script to use throttled-request (found through NPM) which wraps request with a throttling mechanism. 
It may very well be that my implementation is not the way you would want to go, but I have included my patched copy just as an example.
[poloniex.js.txt](https://github.com/dutu/poloniex-api-node/files/1355126/poloniex.js.txt)

**Comment by dutu** [comment]
Thanks @Goswinus .

In my view the API calls throttling should rather be part of the application using the API wrapper (this module), rather than being implemented in the API wrapper itself.

I think your example would be very useful for devs to integrate into their applications.

**Comment by polearnik** [comment]
I think that it is a good idea - requests throtling. Otherwise keeping in mind limit for 6 requests per second, users can be unnexpectedly blocked by Poloniex on a production which can provoke unpleasant consequinces. Also you can add an additional setup for throtling if you consider this optional. Something like
```
 poloniex.openWebSocket({
    version: 2,
    throttling: true,
});
```
