### ISSUE TITLE
Poloniex error 422

### ISSUE THREAD

**Issue by sameepsi** [dutu/poloniex-api-node#26]
I am receiving this error while executing private apis
Poloniex error 422: . Nonce must be greater than 150711082672900. You provided 150711082671300.

**Comment by dutu** [comment]
Please generate a new API key and make sure you only use the API key for one application.

Also to note that nonce errors can occur if you execute API calls in parallel or right after each-other.
Poloniex requires that subsequent API calls to have an ever increasing nonce. When two API calls are sent right one after the other, it may happen that the second API calls (with higher nonce) reaches Poloniex server before the first API call. In this case Poloniex will issue nonce error 422, since nonce are not in increase order.
To avoid this issue you may consider issuing the API calls synchronously (issue a call only when the response from previous call has been received).

Hope this helps.

**Comment by nsnikolaev** [comment]
I have: "Poloniex error 422: . Nonce must be greater than 1573038171160165. You provided 157719741402400."

BUT! 
1573038171160165 - 16 digits
157719741402400 - 15 digits

What this???
