### ISSUE TITLE
ESOCKETTIMEDOUT error on private API requests

### ISSUE THREAD

**Issue by findbl0k** [dutu/poloniex-api-node#4]
Hi,

I am getting an ESOCKETTIMEDOUT error when using private API methods (e.g. returnBalances). I do not get this error when using public API methods (e.g. returnOrderBook). Increasing the timeout option on the request to something like 30000ms fixes this for me. I never got this error before the past few weeks. 
I'm not sure if this is related to recent Poloniex DDOS mitigation measures. Sometimes (~10% of the time) I can get a response without increasing the timeout. But more often, the request times out before Poloniex sends the response.

Here's my fix below:

```
// Make an API request
            options.timeout = 30000; //was 3000ms
```

This is not an ideal fix. Any thoughts?

**Comment by dutu** [comment]
@findbl0k, I also get a lot of ESOCKETTIMEDOUT and ETIMEDOUT error since a day ago. I have the same issue from several other applications. It seams to be a problem with Poloniex servers, as the issue only occurred very sporadically before.

From what I see until now, it doesn't look the issue is triggered by too frequent API calls.

I'll investigate a little bit more to see if there is a workaround or it is a transient Poloniex error.
I'll post an update soon.

**Comment by findbl0k** [comment]
@dutu, thanks for the reply. I'll continue to use the above fix (increasing the response timeout to 30000) for the time being.

**Comment by dutu** [comment]
Just opened Poloniex front web page, it looks Poloniex servers are responding extremely slow.
Check the times here:

![](http://i.imgur.com/cZHoMrI.jpg)

You can use the workaround you mentioned in the meantime.

**Comment by dutu** [comment]
@findbl0k, can you confirm the issue is not present anymore (with the original value `options.timeout = 3000;`

It looks it was a transient Poloniex server malfunction

**Comment by findbl0k** [comment]
@dutu, looks like this was a transient server issue since poloniex was under high load. No problems in the last week. Good to close it.

**Comment by dutu** [comment]
see version 1.1.0 with updates related to socket timeout 
https://github.com/dutu/poloniex-api-node/blob/master/CHANGELOG.md

**Comment by kzs985** [comment]
Anyone else getting ridiculous response times? For example these are my response times for 10 consequent returnBalances calls right now:
4977 ms
860 ms
701 ms
34688 ms
328 ms
321 ms
3939 ms
353 ms
3992 ms
35042 ms
10-30 second is not rare at all... This is a constant problem for me in the last 2 weeks since I'm trying to use poloniex..
Additionally, with 10 seconds timeout I get this error after the third call:
'Error: Poloniex error 429: Too Many Requests. This IP has been banned for 2 minutes. Please adjust your timeout to 130 seconds.'
Any thoughts?

**Comment by dutu** [comment]
@kzs985 

* your observation is adding to what we've see lately: very long response times from Poloniex. In a support ticket response, Poloniex indicated
> To be safe, we would recommend a timeout of 130 seconds; usually though, you would receive a response much sooner.

* Error: `Poloniex error 429: Too Many Requests. This IP has been banned for 2 minutes. Please adjust your timeout to 130 seconds.` seems not to be triggered if you set a `socketTimeout` greater than 60 seconds.

To conclude: Poloniex API responses are seen with long response time,  you should consider setting `socketTimeout` to 60 seconds or more.
