### ISSUE TITLE
websocket connection

### ISSUE THREAD

**Issue by ashok1236** [dutu/poloniex-api-node#60]
I am trying to connect to websocket, but it's returning 403 error with version 2 and not reachable on version 1

**Comment by ashok1236** [comment]
I am also using proxy agent as suggested in another ticket

**Comment by theonlyfox** [comment]
Code please.
Also, check to see if you can get browser requests through using the same proxy.  Could be a bad or blocked proxy.  Clickie and see if you get a response: [https://poloniex.com/public?currencyPair=USDT_BTC&start=1517808279&end=1517828279&limit=300&command=returnTradeHistory](uhttps://poloniex.com/public?currencyPair=USDT_BTC&start=1517808279&end=1517828279&limit=300&command=returnTradeHistoryrl)

**Comment by theonlyfox** [comment]
First: edit this post and remove the API and secret, then go to polo and kill that API key.  Hopefully you only have it set to view and not trade and pray not transfer. Do it now and read the rest of this response after.

Ok, I'm not an expert by any stretch but your code looks fine.  The problem lies with your proxy.  Firstly, and error 403 is indicating that the server is denying a connection because the referring ip is blacklisted either by the server or most likely clouldflare.   This is backed up by you being forced to do a bot check when you went to that web address I sent you.  Try some different proxy addresses, but with socks being an open free proxy system, most of the available proxies would most likely be black listed vs. a paid proxy.

**Comment by ashok1236** [comment]
This api key and secret are for trial purpose only. So no harm there.How can I white list my ip again?

**Comment by dutu** [comment]
can you try
`var proxy = 'socks://192.210.170.171:1080';`

**Comment by ashok1236** [comment]
yup , working like charm

**Comment by ashok1236** [comment]
so problem lies, with in ip blacklisting. Thanks for your help, I will try to find ip, which are not blacklisted

**Comment by ashok1236** [comment]
Ok, another problem, I don't think I am getting live data,it seems to be 5 hours off

**Comment by dutu** [comment]
@ashok1236 , please verify the timestamp properly. Also you can check the orderbook sequence numbers you receive on WebSocket and REST API to see if any large gaps between them.

In anycase, this library passes the results as received from Poloniex. If any data is off for a number of hours, please query the issue with Poloniex support.
