### ISSUE TITLE
error Nonce

### ISSUE THREAD

**Issue by steeply** [dutu/poloniex-api-node#8]
The error with Nonce you do not work in any way?

`Error: Poloniex error 422: Nonce must be greater than 1492403545596268. You provided 149266840128300.`

There is also no possibility to set it manually. How can I fix it?
In your code, 
> _private: function(command, parameters, callback){
> let param = parameters;
> **param.nonce = nonce (16);**

 Closed for manual update in case of such an error.

Can you handle this error yourself or add an set-nonce method?
>   set-nonce: (nonce) !->
>     @poloniex.nonce = nonce

**Comment by dutu** [comment]
@steeply, if you get a nonce error frequently it is most likely because using the same API key from another application. The resolve this, please generate and use a new API key.

The nonce is used to make each request unique; the nonce parameter is an integer which must always be greater than the previous nonce used. To achieve this unix timestamp is used.
It's not really possible handling the error in a different way other than showing the error to the user.
You'll just need to ensure  the API key is not used somewhere else and then everything should be fine.

**Comment by steeply** [comment]
Api keys used in 1 app. But this key can be inserted from another application. Well, of course, 1 clean key for new application.

Asynchronous requests in the application will correctly work?

**Comment by dutu** [comment]
yes, the asynchronously requests are correctly sent

**Comment by steeply** [comment]
thanks for the advice
